AUG:
  TEST_CROP: true
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - Birds
    DATASET_ROOTS:
    -
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 10000
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 1
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME:
  PRETRAINED:
  TYPE: Episodic_Model_knn
OUTPUT:
